// Routes for the reports module.
//
// Surface:
//   GET /reports/teller-commissions   admin   per-teller commission leaderboard
//   GET /reports/fight-commissions    admin   per-fight commission table
//
// Remaining Tier 3: `/reports/session`, `/reports/teller/{id}`.

import { getFightCommissions, getTellerCommissions } from './reports.service.js'
import {
  fightCommissionsQuerySchema,
  fightCommissionsResponseSchema,
  tellerCommissionsQuerySchema,
  tellerCommissionsResponseSchema
} from './reports.schemas.js'
import { errorResponses } from '../../lib/api-schemas.js'

const tags = ['Reports']
const security = [{ bearerAuth: [] }]

export default async function reportsRoutes(app) {
  const adminOnly = [app.authenticate, app.requireRole('ADMIN')]

  // -------------------------------------------------------------------------
  // GET /reports/teller-commissions
  // -------------------------------------------------------------------------
  app.get(
    '/teller-commissions',
    {
      preHandler: adminOnly,
      schema: {
        tags,
        summary: 'Per-teller commission attribution (admin leaderboard)',
        description:
          'Admin-only. Returns the running commission generated by each ' +
          'teller, attributed proportionally from the house commission take. ' +
          'Use this for productivity ranking, shift reports, and night-end ' +
          'reconciliation.\n\n' +
          '### The math\n' +
          'Commission is parimutuel — the house takes `commissionRate` of ' +
          'the entire pool. Each peso of stake contributes `commissionRate` ' +
          'pesos of commission regardless of whether it won or lost. So:\n\n' +
          '```\n' +
          'commissionGenerated(teller) =\n' +
          '  SUM_over_bets( bet.stake × (bet.fight.commissionRate / 2) )\n' +
          '```\n\n' +
          'The rate is SNAPSHOTTED per fight, so this is correct even if ' +
          '`Setting.commissionRate` is changed mid-session.\n\n' +
          '### Which bets count\n' +
          '| status | counts? | why |\n' +
          '|---|---|---|\n' +
          '| `WON` / `LOST` / `PAID` | ✅ | fight settled with MERON/WALA outcome; house took commission |\n' +
          '| `REFUNDED` | ❌ | DRAW / CANCELLED → no commission was taken |\n' +
          '| `VOIDED` | ❌ | pulled pre-settle, pool decremented, no commission |\n' +
          '| `PENDING` | ❌ | fight not yet settled; commission not yet realized |\n\n' +
          '### Real-time updates\n' +
          'Whenever a fight transitions in a way that mutates realized ' +
          'commission (settle, cancel, correct), the server broadcasts ' +
          'a `TELLER_COMMISSIONS_UPDATED` frame on `/ws`. Admin dashboards ' +
          'should listen for that frame and re-issue this request with ' +
          'their current filter scope.\n\n' +
          '### Sanity invariant\n' +
          '`SUM(tellers[i].commissionGenerated) === totals.commissionGenerated`. ' +
          'If they drift, there is a bug — file an issue.',
        operationId: 'reportsTellerCommissions',
        security,
        querystring: tellerCommissionsQuerySchema,
        response: {
          ...tellerCommissionsResponseSchema,
          400: errorResponses[400],
          401: errorResponses[401],
          403: errorResponses[403],
          500: errorResponses[500]
        }
      }
    },
    async (request) => getTellerCommissions(request.server.prisma, request.query)
  )

  // -------------------------------------------------------------------------
  // GET /reports/fight-commissions — per-fight commission
  // -------------------------------------------------------------------------
  app.get(
    '/fight-commissions',
    {
      preHandler: adminOnly,
      schema: {
        tags,
        summary: 'Per-fight house commission (admin)',
        description:
          'Admin-only. Returns one row per fight with gross handle (frozen pools) ' +
          'and house commission (SETTLED MERON/WALA only: gross × commissionRate / 2). ' +
          'Sorted by fight number descending.\n\n' +
          'SUM(fights[i].commission) should match realized commission for the session. ' +
          'Refresh when `FIGHT_SETTLED`, `FIGHT_CORRECTED`, or `FIGHT_CANCELLED` fires on `/ws`.',
        operationId: 'reportsFightCommissions',
        security,
        querystring: fightCommissionsQuerySchema,
        response: {
          ...fightCommissionsResponseSchema,
          400: errorResponses[400],
          401: errorResponses[401],
          403: errorResponses[403],
          500: errorResponses[500]
        }
      }
    },
    async (request) => getFightCommissions(request.server.prisma, request.query)
  )
}
